# Inventory files use an ini-like structure by default, but can also be written in YAML format
# https://docs.ansible.com/ansible/latest/network/user_guide/network_best_practices_2.5.html#groups-and-variables-in-an-inventory-file

#!! Instead of plaintext login credentials here, it is recommended to use the Ansible Vault
# https://docs.ansible.com/ansible/latest/network/user_guide/network_best_practices_2.5.html#ansible-vault-for-password-encryption

# [all:vars] contains default variables that all groups inherit
[all:vars]
ansible_connection=network_cli
ansible_network_os=ios
ansible_user=admin
ansible_password=ciscossh
ansible_become=yes
ansible_become_method=enable
ansible_become_password=class

# [<group>] contains subgroups of devices that can have their own variables
#?? <hostname> ansible_host=<ip address>
[routers]
R1 ansible_host=192.168.15.254

[switches]
S1 ansible_host=192.168.15.253
