# Default variables that all sections inherit
[all:vars]
ansible_connection=network_cli
ansible_network_os=ios
ansible_user=admin
ansible_password=ciscossh
ansible_become=yes
ansible_become_method=enable
ansible_become_password=class

# Groups of devices that can have their own variables
[routers]
192.168.15.254

[switches]
192.168.15.253
